# Generated by Django 5.0 on 2023-12-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='announcements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.announcement'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='announcements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.announcement'),
        ),
    ]
