# Generated by Django 5.0 on 2024-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_companyprofile_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='surface',
            field=models.IntegerField(null=True),
        ),
    ]
